# Generated by Django 3.0.5 on 2024-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='hint1',
            field=models.CharField(default=str, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='hint2',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
