# Generated by Django 3.0.5 on 2024-07-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20240514_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='solution_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
